### ISSUE TITLE
Encoding issues

### ISSUE THREAD

**Issue by cppcooper** [kevr/hastebin#3]
The script seems to have a problem with utf-8

```
Traceback (most recent call last):
  File "/usr/bin/hastebin", line 135, in <module>
    e = main()
  File "/usr/bin/hastebin", line 116, in main
    return_code, response = post_paste(stdin)
  File "/usr/bin/hastebin", line 46, in post_paste
    response = requests.post(post_url,
  File "/usr/lib/python3.10/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1327, in _send_request
    body = _encode(body, 'body')
  File "/usr/lib/python3.10/http/client.py", line 166, in _encode
    raise UnicodeEncodeError(
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2018' in position 1853: Body ('‘') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.
```

**Comment by massimopavoni** [comment]
Same here, was trying to use this for a journalctl log share...

**Comment by kevr** [comment]
Thanks, I'll work on this.

**Comment by kevr** [comment]
utf-8 fix: https://github.com/kevr/hastebin/pull/5 merged

However, I've been away from this project for quite a while, it seems they've changed the API to now require a Github token. So, that'll require another PR and requirement of using a github token with hastebin. I'm working on it now before the utf merge.

API change: https://github.com/kevr/hastebin/pull/7 merged
